name: face-app
channels:
- defaults
dependencies:
- certifi=2016.2.28=py35_0
- mkl=2017.0.3=0
- numpy=1.13.1=py35_0
- openssl=1.0.2l=0
- pip=9.0.1=py35_1
- python=3.5.4=0
- readline=6.2=2
- setuptools=36.4.0=py35_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - absl-py==0.1.13
  - astor==0.6.2
  - bleach==1.5.0
  - click==6.7
  - flask==0.12.2
  - gast==0.2.0
  - gevent==1.2.2
  - greenlet==0.4.13
  - grpcio==1.11.0
  - gunicorn==19.7.1
  - h5py==2.7.1
  - html5lib==0.9999999
  - itsdangerous==0.24
  - jinja2==2.10
  - keras==2.1.5
  - markdown==2.6.11
  - markupsafe==1.0
  - pillow==5.1.0
  - protobuf==3.5.2.post1
  - pyyaml==3.12
  - scipy==1.0.1
  - six==1.11.0
  - tensorboard==1.7.0
  - tensorflow==1.7.0
  - termcolor==1.1.0
  - werkzeug==0.14.1

