name: face-app
channels:
- defaults
dependencies:
- bleach=1.5.0=py35_0
- certifi=2016.2.28=py35_0
- html5lib=0.9999999=py35_0
- ipykernel=4.6.1=py35_0
- ipython=5.0.0=py35_0
- ipywidgets=6.0.0=py35_0
- jinja2=2.9.6=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=5.1.0=py35_0
- jupyter_console=5.2.0=py35_0
- jupyter_core=4.3.0=py35_0
- mkl=2017.0.3=0
- nbconvert=5.2.1=py35_0
- nbformat=4.4.0=py35_0
- notebook=5.0.0=py35_0
- numpy=1.13.1=py35_0
- openssl=1.0.2l=0
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_1
- prompt_toolkit=1.0.15=py35_0
- pyqt=5.6.0=py35_2
- python=3.5.4=0
- python-dateutil=2.6.1=py35_0
- pyzmq=16.0.2=py35_0
- qtconsole=4.3.1=py35_0
- readline=6.2=2
- setuptools=36.4.0=py35_1
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- testpath=0.3.1=py35_0
- tk=8.5.18=0
- tornado=4.5.2=py35_0
- traitlets=4.3.2=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=3.0.2=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - absl-py==0.1.13
  - astor==0.6.2
  - click==6.7
  - flask==0.12.2
  - gast==0.2.0
  - gevent==1.2.2
  - greenlet==0.4.13
  - grpcio==1.11.0
  - gunicorn==19.7.1
  - h5py==2.7.1
  - itsdangerous==0.24
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - keras==2.1.5
  - markdown==2.6.11
  - markupsafe==1.0
  - opencv-python==3.4.0.12
  - pillow==5.1.0
  - prompt-toolkit==1.0.15
  - protobuf==3.5.2.post1
  - pyyaml==3.12
  - scipy==1.0.1
  - tensorboard==1.7.0
  - tensorflow==1.7.0
  - termcolor==1.1.0
  - werkzeug==0.14.1

